version: "2"

services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_JSON:/config.json:ro
    network_mode: $NETWORK
    container_name: watchtower
    hostname: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=$SLACK_HOOK_URL
    command: --cleanup
    restart: always
